# Generated by Django 5.1.3 on 2024-11-24 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, help_text='Укажите место выполнения привычки', max_length=100, null=True, verbose_name='Место выполнения привычки')),
                ('start_time', models.DateTimeField(help_text='Выберете дату и время начала привычки', verbose_name='Время начала выполнения привычки')),
                ('action', models.CharField(help_text='Опишите действие вашей привычки', max_length=300, verbose_name='Действие привычки')),
                ('is_pleasant', models.BooleanField(default=False, help_text='Привычка является приятной', verbose_name='Признак приятной привычки')),
                ('rhythm', models.CharField(choices=[('every day', 'каждый день'), ('every other day', 'чере день'), ('every three days', 'раз в 3 дня'), ('every four days', 'раз в 4 дня'), ('every five days', 'раз в 5 дней'), ('every six days', 'ра в 6 дней'), ('every weak', 'раз в неделю')], help_text='Выберите переодичностьт выполнения привычки', max_length=16, verbose_name='Переодичность выполнения')),
                ('reward', models.CharField(blank=True, help_text='Укажите вознаграждение', max_length=300, null=True, verbose_name='Вознаграждение')),
                ('lead_time', models.IntegerField(help_text='Укажите предположительное время выполнения привычки в минутах', verbose_name='Время выполнения')),
                ('is_published', models.BooleanField(default=False, help_text='Опубликовать для общего доступа', verbose_name='Общий доступ')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('related_habit', models.ForeignKey(blank=True, help_text='Выбирите связанную приятную привычку', null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка')),
            ],
        ),
    ]
