# Generated by Django 5.1.3 on 2024-12-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="start_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Выберете дату и время начала привычки",
                null=True,
                verbose_name="Время начала выполнения привычки",
            ),
        ),
    ]
