# Generated by Django 5.1.3 on 2024-12-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="lead_time",
            field=models.IntegerField(
                default=1,
                help_text="Укажите предположительное время выполнения привычки в минутах",
                verbose_name="Время выполнения",
            ),
        ),
    ]
