# Generated by Django 5.1.3 on 2024-12-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_lead_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="rhythm",
            field=models.CharField(
                choices=[
                    ("every day", "каждый день"),
                    ("every other day", "чере день"),
                    ("every three days", "раз в 3 дня"),
                    ("every four days", "раз в 4 дня"),
                    ("every five days", "раз в 5 дней"),
                    ("every six days", "ра в 6 дней"),
                    ("every weak", "раз в неделю"),
                ],
                default="every day",
                help_text="Выберите переодичностьт выполнения привычки",
                max_length=16,
                verbose_name="Переодичность выполнения",
            ),
        ),
    ]
